---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# Build targets can be found at:
# On PR: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/
# On commit: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/

specfile_path: gvisor-tap-vsock.spec

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    owner: rhcontainerbot
    project: packit-builds
    enable_net: true
    srpm_build_deps:
      - make
      - rpkg
    targets:
      - fedora-rawhide-aarch64
      - fedora-rawhide-x86_64
      - fedora-eln-aarch64
      - fedora-eln-x86_64
      - fedora-38-aarch64
      - fedora-38-x86_64
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - centos-stream-8-aarch64
      - centos-stream-8-x86_64
    actions:
      post-upstream-clone:
        - "rpkg spec --outdir ./"
      fix-spec-file:
        - "bash .packit.sh"

    #- <<: *copr
    # Run on commit to main branch
    #trigger: commit
    #branch: main
    #project: podman-next
    #targets:
    #  - fedora-rawhide-aarch64
    #  - fedora-rawhide-x86_64
    #  - fedora-eln-aarch64
    #  - fedora-eln-x86_64
    #  - fedora-38-aarch64
    #  - fedora-38-x86_64
    #  - centos-stream-9-aarch64
    #  - centos-stream-9-x86_64
    #  - centos-stream-8-aarch64
    #  - centos-stream-8-x86_64
