name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make cross qemu-wrapper vm

    - uses: actions/upload-artifact@v2
      with:
        name: gvproxy
        path: bin/gvproxy*

  tests:
    runs-on: macos-11 # Only Mac runners support nested virt
    needs: build # Don't bother testing if cross arch build fails
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        brew install qemu
        touch continue

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make test
